spring:
  datasource:
    url: jdbc:mysql://localhost:33306/qbao?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  name: chongge1
  redis:
    host: localhost
    port: 6379
    password:
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
